function createfigureLevelSetFunction3D(xdata1, ydata1, zdata1, zdata2, cdata1)
%CREATEFIGURE(XDATA1, YDATA1, ZDATA1, ZDATA2, CDATA1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  ZDATA2:  surface zdata
%  CDATA1:  surface cdata

%  Auto-generated by MATLAB on 12-Apr-2015 12:21:35

% Create figure
figure1 = figure(4);
colormap('winter');

% Create axes
axes1 = axes('Parent',figure1);
view(axes1,[-37.5 30]);
grid(axes1,'on');
hold(axes1,'all');

% Create surf
surf(xdata1,ydata1,zdata1,'Parent',axes1,'EdgeColor','none');

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

% Create surf

figure(5)
surf(xdata1,ydata1,zdata2,cdata1,'Parent',axes1,'EdgeColor','none');

% contour3 currently does not support code generation, enter 'doc contour3' for correct input syntax

% contour3(...);

